### KEGG GSEA

GSEA but using the KEGG dataset.

```{r kegg-gsea}
#| fig-width: 8
#| fig-height: 10.5
#| fig-align: center

listy_prot_kegg_gsea <- list()

if (inherits(df_limma, "list")){
  
  for(i in 1:length(df_limma)){
    
    protlist <- df_limma[[i]] %>% 
      dplyr::select(Protein.IDs,
                    logFC) %>% 
      na.omit() %>% 
      arrange(-logFC) %>% 
      tibble::deframe()
    
    egsea <- clusterProfiler::gseKEGG(geneList     = protlist,
                                      organism     = kegg_code,
                                      keyType = "uniprot",
                                      pvalueCutoff = 0.05,
                                      verbose      = FALSE)
    
    listy_prot_kegg_gsea[[i]] <- egsea
    names(listy_prot_kegg_gsea)[i] <- names(df_limma)[i]
    
  }
}

listy_prot_kegg_gsea <- purrr::list_flatten(listy_prot_kegg_gsea)


for (j in 1:length(listy_prot_kegg_gsea)){
  foo <- listy_prot_kegg_gsea[[j]]
  
  if(nrow(foo@result[which(foo@result$p.adjust < 0.05),]) > 0){
    
    print(clusterProfiler::ridgeplot(foo) +
          scale_y_discrete(labels = function(x) stringr::str_wrap(x, width = 30)) +
          ggplot2::labs(title = comp_labels[names(listy_prot_kegg_gsea)[j]]) +
          theme(axis.text.y = element_text(size = 11)))
    
  } else {
    cat("No significantly enriched GSEA terms.\n")
  }
}

```

```{r}
kegg_gsea_exp <- purrr::map(listy_prot_kegg_gsea, ~.x@result) %>% 
  purrr::discard(~ nrow(.x) == 0)

openxlsx::write.xlsx(kegg_gsea_exp, file = paste0("results/",
                                                  format(Sys.time(), "%Y%m%d"),
                                                  exp_id,
                                                  "_proteome_GSEA_KEGG.xlsx"))
```